spring:
  shardingsphere:
    # 数据源相关配置
    datasource:
      # 数据源名称
      names: master,s1,s2
      # MySQL master数据源
      master:
        # 数据库连接池
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/trade1
        username: root
        password: 123456
      # 两个slave数据源
      s1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/trade2
        username: root
        password: 123456
      s2:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/trade3
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names:
        - s1
        - s2
    # 其他属性
    props:
      # 开启SQL显示
      sql.show: false
mybatis:
  mapper-locations: classpath*:/mapper/*.xml